config/routes.rb
Tasks::Application.routes.draw do

 
  resources :users

  root to: "home#index"
  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :priority
  
  validates_presence_of :description
  validates_uniqueness_of :description
  validates :priority, numericality: {:greater_than => 0}

  before_validation :clean_description, if: "description.present?"

  private
  
  def clean_description
	self.description = self.description.strip.capitalize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
	@tasks = Task.all
  end

  def show
	@task = Task.find(params[:id])
  end

  def new
	@task =Task.new
  end

  def create
	@task = Task.create(params[:task])
	if @task.save	 
	  redirect_to @task
	else
	  render :new
	end

  end

  def edit
	@task = Task.find(params[:id])
  end

  def update
	@task = Task.find(params[:id])
    	if @task.update_attributes(params[:task])
       	 	redirect_to @task
    	else
        	render :edit
    end
  end

  def destroy
	Task.find_by_id(params[:id]).try(:delete)
    	redirect_to tasks_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Tasks app</h1>

<%= link_to "See all tasks", tasks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  
  <% if @task.errors.any? %>
      <h2>Invalid task, the errors were:</h2>
      <ul>
          <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
      </ul>
  <% end %>


  <p>
	<%= f.label :description %>
	<%= f.text_area :description %>
  </p>

  <p>
	<%= f.label :priority %>
	<%= f.number_field :priority %>
  </p>
  <p>
	<%= f.submit %>
  </p>

<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit a task:</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1><%= link_to "Tasks", root_path %></h1>
<ol>
  <% @tasks.each do |task| %>
  <li>
	<%= task.description %>
	<%= link_to "Show", task %>
	<%= link_to "Edit", edit_task_path(task) %>	
	<%= link_to "Delete", task, :method => :delete, :confirm => "are you sure?" %>
  </li>

  <% end %>
</ol>
<%= link_to "create new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>Create a Task</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Task id:<%= @task.id %> </h1>
<p>
	Task with description <%= @task.description %>
	and priority <%= @task.priority %>

</p>

<%= link_to "All Tasks", tasks_path %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.username %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>